apiVersion: v1
kind: Service
metadata:
  name: ms-company
  labels:
    app: ms-company
spec:
  selector:
    app: ms-company
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
